name: Setup

description: |
  setup fot github actions

inputs:
  token:
    description: The token to use for the setup.
    required: true
  bot-app-slug:
    description: The app slug for the bot.
    required: true

runs:
  using: composite
  steps:
    - name: Setup Git User
      shell: bash
      run: |
        user_name=${{ inputs.bot-app-slug }}[bot]
        user_email=$(gh api "/users/${{ inputs.bot-app-slug }}[bot]" --jq .id)+${{ inputs.bot-app-slug }}[bot]@users.noreply.github.com
        echo "Setting up git user: $user_name <$user_email>"
        git config --global user.name $user_name
        git config --global user.email $user_email
      env:
        GH_TOKEN: ${{ inputs.token }}
    - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version-file: .node-version
    - name: Setup pnpm
      shell: bash
      run: corepack enable pnpm
    - name: Setup turbo
      shell: bash
      run: |
        echo "TURBO_CACHE_DIR=${{ runner.temp }}/turbo" >> $GITHUB_ENV
    - uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4
      with:
        path: ${{ runner.temp }}/turbo
        key: ${{ runner.os }}-turbo-${{ github.workflow }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-${{ github.workflow }}
          ${{ runner.os }}-turbo-
