name: create changeset for PR created by Renovate

on:
  pull_request:
    branches:
      - main

jobs:
  default:
    runs-on: ubuntu-latest
    # commit author should be renovate[bot]
    if: startsWith(github.head_ref, 'renovate/') && github.event.pull_request.user.login == 'renovate[bot]' && github.actor == 'renovate[bot]'
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ steps.app-token.outputs.token }}
      - uses: ./.github/actions/setup
        with:
          token: ${{ steps.app-token.outputs.token }}
          bot-app-slug: ${{ steps.app-token.outputs.app-slug }}
      - uses: YutaUra/actions/renovate-changeset@30c1d5ca65093f4f15fa1c942be647760d0729da # v0.0.111
        with:
          token: ${{ steps.app-token.outputs.token }}
          setup-git-user: false
